title                   : Swanky Docs - API Documentation
repo                    : https://github.com
version                 : 0.0.0
src                     : src
theme                   : src/themes/docs-theme
output                  : docs
serverPath              : docs

sections                :

  - title               : Overview
    content             : 'src/content/overview.md'
